#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("VKSaver.Android.Resource", IsApplication=true)]

namespace VKSaver.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::VKSaver.Android.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::VKSaver.Android.Resource.String.Hello;
			global::SQLite.Net.Platform.XamarinAndroidN.Resource.String.ApplicationName = global::VKSaver.Android.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroidN.Resource.String.Hello = global::VKSaver.Android.Resource.String.Hello;
			global::VKSaver.Core.FileSystem.Resource.String.ApplicationName = global::VKSaver.Android.Resource.String.ApplicationName;
			global::VKSaver.Core.FileSystem.Resource.String.Hello = global::VKSaver.Android.Resource.String.Hello;
			global::VKSaver.Core.LinksExtractor.Android.Resource.String.ApplicationName = global::VKSaver.Android.Resource.String.ApplicationName;
			global::VKSaver.Core.LinksExtractor.Android.Resource.String.Hello = global::VKSaver.Android.Resource.String.Hello;
			global::VKSaver.Core.Models.Resource.String.ApplicationName = global::VKSaver.Android.Resource.String.ApplicationName;
			global::VKSaver.Core.Models.Resource.String.Hello = global::VKSaver.Android.Resource.String.Hello;
			global::VKSaver.Core.Toolkit.Resource.String.ApplicationName = global::VKSaver.Android.Resource.String.ApplicationName;
			global::VKSaver.Core.Toolkit.Resource.String.Hello = global::VKSaver.Android.Resource.String.Hello;
			global::VKSaver.Core.ViewModels.Resource.String.ApplicationName = global::VKSaver.Android.Resource.String.ApplicationName;
			global::VKSaver.Core.ViewModels.Resource.String.Hello = global::VKSaver.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int vksaver_accent_high = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int vksaver_accent_low = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int vksaver_accent_medium = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Logo = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int AuthTextView = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int LoginButton = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int LoginEditText = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int LogoImageView = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int PasswordEditText = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int SplashImageView = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int LoginActivity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int SplashScreenActivity = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int LoginActivity_AuthText = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int LoginActivity_LoginText = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
